trigger:
  batch: true
  branches:
    include:
    - cccs-main

variables:
  containerRegistry: uchimera
  imageRepository: cccs/trino
  buildTimestamp: $[format('{0:yyyyMMddHHmmss}', pipeline.startTime)]
  DOCKER_BUILDKIT: 1

pool:
  vmImage: ubuntu-latest

steps:
- bash: |
    BRANCH_NAME=$(echo "$SYSTEM_PULLREQUEST_SOURCEBRANCH $BUILD_SOURCEBRANCH" | sed -r 's/^\s*(refs\/heads\/)?(\S*).*$/\2/' | sed 's/\//_/g')
    echo "##vso[task.setvariable variable=BRANCH_NAME]$BRANCH_NAME"
  displayName: Parse Source Control Branch Name
- bash: $(Build.SourcesDirectory)/mvnw clean install -DskipTests
  displayName: Maven build
- bash: |
    cd $(Build.SourcesDirectory)/core/docker
    ./build-local.sh
    if [ $? -ne 0 ]; then
      echo "Docker build failed"
      exit 1
    fi

    set -euxo pipefail
    cd $(Build.SourcesDirectory)
    TRINO_VERSION=$(./mvnw --quiet help:evaluate -Dexpression=project.version -DforceStdout)
    echo "##vso[task.setvariable variable=TRINO_VERSION]$TRINO_VERSION"

    docker tag trino:${TRINO_VERSION} $(imageRepository):$(BRANCH_NAME)_v${TRINO_VERSION}
    docker tag trino:${TRINO_VERSION} $(imageRepository):$(BRANCH_NAME)_v${TRINO_VERSION}_$(buildTimestamp)_b$(Build.BuildId)
  displayName: Docker build
- task: Docker@2
  displayName: Login to $(containerRegistry)
  inputs:
    containerRegistry: $(containerRegistry)
    command: login
- task: Docker@2
  displayName: Push image to container registry
  inputs:
    containerRegistry: $(containerRegistry)
    command: push
    repository: $(imageRepository)
    tags: |
      $(BRANCH_NAME)_v$(TRINO_VERSION)
      $(BRANCH_NAME)_v$(TRINO_VERSION)_$(buildTimestamp)_b$(Build.BuildId)
- task: Docker@2
  displayName: Logout of $(containerRegistry)
  inputs:
    command: logout
    containerRegistry: $(containerRegistry)
